### ISSUE TITLE
Sbt NgAnnotateKeys._ Unknown

### ISSUE THREAD

**Issue by abelbryo** [buddho-io/sbt-ng-annotate#1]
Hi, 

How do I add the plugin in my project, I tried it in different ways to no avail.  Is there some easy way to do something like this ?
 `addSbtPlugin("com.github.buddho-io" % "sbt-ng-annotate" % "1.0-SNAPSHOT")`

**Comment by llinder** [comment]
@abelbryo the best example I have right now is the project I use to test things:
https://github.com/buddho-io/sbt-ng-annotate/tree/master/src/sbt-test/sbt-ng-annotate/annotate

try using `addSbtPlugin("io.buddho.sbt" % "sbt-ng-annotate" % "0.1.0-SNAPSHOT")`

then in your build file you should be able to do something as simple as:

```
import NgAnnotateKeys._
import JsEngineKeys._

lazy val root = (project in file(".")).enablePlugins(SbtWeb)

engineType := JsEngineKeys.EngineType.Node

pipelineStages := Seq(ngAnnotate)
```

This isn't deployed to Sonatype OSS repo yet so you will have to checkout the code, build and publish to a local repository as well.

**Comment by abelbryo** [comment]
Thanks Lance! I eventually got the dependency to work but doesn't compile. The error log looks like this.

```
JsTaskFailure: 
module.js:340
    throw err;
          ^
Error: Cannot find module 'jstranspiler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/msard-abel/Projects/tuts/test-play/target/web/ngAnnotate/sbt-ng-annotate.jar:7:9
    at Object.<anonymous> (/Users/msard-abel/Projects/tuts/test-play/target/web/ngAnnotate/sbt-ng-annotate.jar:89:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by abelbryo** [comment]
It turned out, copying the `package.json` into my project and run `npm install` solves the problem. 
Thanks very much!

**Comment by llinder** [comment]
Ah yes, that part slipped my mind. Honestly haven't been using this much yet. There are a few more plugins I need before completely moving off Grunt. Hopefully in the future I will have more time to document these thing better.
